sudo: required
dist: xenial
language:
  - python
python:
  - "3.7"
addons:
  apt:
    sources:
      - sourceline: "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8"
        key_url: "https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg"
    packages:
      - bazel

install:
  - go get -u github.com/bazelbuild/buildifier/buildifier
  - pip uninstall -y pip setuptools wheels

script:
  # Check for issues with the format of our bazel config files.
  - buildifier -mode=check $(find . -type f -name '*.bzl' -o -name WORKSPACE -o -name BUILD)

  # Check that all of our tests pass
  - bazel clean && bazel test --config=ci //...
  - bazel clean && bazel test --config=ci //...
